server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hzy?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Hzy123456..


mybatis-plus:
  type-aliases-package: cn.edu.guet.insuranceandmove.bean
  mapper-locations: classpath:mapper/*Mapper.xml

#showSql
logging:
  level:
    cn.edu.guet.insurance.mapper: DEBUG